### ISSUE TITLE
Create initialize.sql for local DB setup

### ISSUE THREAD

**Issue by 3watermelons** [3watermelons/Banking-System#8]
I have attached a word file containing SQL queries but it has extra code injected during the conversion

**The code must**
- create DB 
- create tables
- insert dummy customers 

Take the required code snippets and put it into a .sql file

**Comment by siddhesh-desai** [comment]
Hello, I would like to solve this. Please assign it to me. Thankyou

**Comment by 3watermelons** [comment]
Alright go ahead

**Comment by siddhesh-desai** [comment]
#9 Check this out @3watermelons
